name: media-server

services:

  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - 9091:9091
      - 8889:8888
      - 8989:8989 #radaar
      - 7878:7878 #sonaar
      - 6767:6767 #bazaar
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping --mute-replay-warnings
      - OPENVPN_CONFIG=ca_ontario
      # - LOCAL_NETWORK=192.168.0.0/24
      - LOCAL_NETWORK=10.88.111.0/24
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=5
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/torrents
      - TRANSMISSION_WATCH_DIR=/data/watch
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/transmission:/config
      - ${ROOT}/downloads:/data/torrents
      - ${ROOT}/incomplete:/data/incomplete
      - ${ROOT}/downloads/torrent-blackhole:/data/watch

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${ROOT}/config/plex:/config
      - ${ROOT}/complete/movies:/movies
      - ${ROOT}/complete/tv:/tv
      - ${ROOT}/complete/photos:/photos
    restart: unless-stopped
    ports:
      - 32400:32400

  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes: 
      - ${ROOT}/config/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  jackket:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config
    ports:
      - 9117:9117
  
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    network_mode: "service:transmission"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config
      - ${ROOT}/complete/tv:/tv
      - ${ROOT}/downloads/:/data/torrents
    restart: unless-stopped
    depends_on:
      transmission:
        condition: service_healthy
        restart: true

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    network_mode: "service:transmission"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config
      - ${ROOT}/complete/movies:/movies
      - ${ROOT}/downloads:/data/torrents
    restart: unless-stopped
    depends_on:
      transmission:
        condition: service_healthy
        restart: true
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: "service:transmission"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${ROOT}/complete/movies:/movies
      - ${ROOT}/complete/tv:/tv
    depends_on:
      transmission:
        condition: service_healthy
        restart: true

    expenseowl:
      image: tanq16/expenseowl:main
      restart: unless-stopped
      ports:
        - 5006:8080
      volumes:
        - ${ROOT}/expenseowl:/app/data
      environment:
        - CURRENCY=cad
        - EXPENSE_CATEGORIES=Food,Groceries,Entertainment,Transportation,Healthcare,Shopping,Gifts,Miscellaneous
